In [1]:
import torchvision
from torchvision import transforms
from PIL import Image
import matplotlib.pyplot as plt
from tqdm import tqdm
import numpy as np
import yaml
import os
import torch

In [12]:
cifar10_dataset = torchvision.datasets.CIFAR10(root='/home/chenghua/Data/cifar10/')
cifar100_dataset = torchvision.datasets.CIFAR100(root='/home/chenghua/Data/cifar100/')

In [ ]:
cifar_targets = np.array(cifar10_dataset.targets)
index_0 = np.where(cifar_targets==4)[0]
img = cifar10_dataset.data[index_0[5]] 
plt.imshow(img)
plt.show()

In [ ]:
index_8 = np.where(cifar_targets==8)[0]
img = cifar10_dataset.data[index_8[200]] 
plt.imshow(img)
plt.show()

In [ ]:
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])
cifar10 = torchvision.datasets.CIFAR10(root='/home/chenghua/Data/cifar10/', train=True, download=False, transform=transform)
# trainset = ImbalanceCIFAR10(data_root='/home/waa/Data/CIFAR10/', train=True, download=False, transform=None)

In [20]:
a = torch.randn(size=(2, 5))

In [21]:
a

tensor([[-1.0570,  1.4360,  1.4913, -0.0869,  0.9557],
        [ 0.7305,  2.3317, -0.2251, -1.4884,  0.7062]])

In [23]:
torch.norm(a, dim=1)

tensor([2.5148, 2.9555])

In [1]:
from datetime import datetime

In [13]:
print(datetime.now().strftime('%Y-%m-%d %H:%M:%S'))

2021-12-13 15:36:22


In [25]:
num_classes = 5
index = torch.tensor([1, 3, 4, 0, 2, 2, 4])
torch.zeros(len(index), num_classes, dtype=index.dtype).scatter_(1, index.view(-1, 1), 1)

tensor([[0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1]])

In [26]:
index.view(-1, 1)

tensor([[1],
        [3],
        [4],
        [0],
        [2],
        [2],
        [4]])

In [28]:
type(index)

torch.Tensor

In [53]:
def label2onehot(targets, num_classes):
    if not isinstance(targets, torch.Tensor):
        targets = torch.tensor(targets)
    batch_size = len(targets)
    init_zeros = torch.zeros(batch_size, num_classes)
    return init_zeros.scatter_(1, targets.view(-1, 1), 1)

In [59]:
oh = label2onehot(index, num_classes=9)

In [60]:
oh

tensor([[0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0.]])

In [12]:
a = np.array([[1, 2], [3, 4]])

In [13]:
a

array([[1, 2],
       [3, 4]])

In [22]:
np.sum(a, axis=1)

array([3, 7])

In [23]:
np.diag(a) / np.sum(a, 1)

array([0.33333333, 0.57142857])

In [36]:
a = np.array([[1, 2], [2, 3]])
b = np.array([[3], [5]])

In [38]:
a

array([[1, 2],
       [2, 3]])

In [37]:
b

array([[3],
       [5]])

In [39]:
np.matmul(a,b)

array([[13],
       [21]])

In [44]:
a = torch.randint(3, (2, 2))
b = torch.randint(3, (3, 2))

In [45]:
a

tensor([[0, 1],
        [1, 0]])

In [46]:
b

tensor([[1, 1],
        [1, 0],
        [1, 0]])

In [51]:
m = a.shape[0]
n = b.shape[0]

In [55]:
torch.pow(a, 2).sum(1, keepdim=True).expand(m, n)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [58]:
torch.pow(b, 2).sum(1, keepdim=True).expand(n, m).t()

tensor([[2, 1, 1],
        [2, 1, 1]])

In [60]:
dist = torch.pow(a, 2).sum(1, keepdim=True).expand(m, n) + torch.pow(b, 2).sum(1, keepdim=True).expand(n, m).t()
dist

tensor([[3, 2, 2],
        [3, 2, 2]])

In [61]:
torch.pow(dist, 1/2)

tensor([[1.7321, 1.4142, 1.4142],
        [1.7321, 1.4142, 1.4142]])

In [63]:
torch.square(torch.sqrt(dist))

tensor([[3.0000, 2.0000, 2.0000],
        [3.0000, 2.0000, 2.0000]])

In [69]:
a = torch.tensor([[3,4], [6,8]]).float()

In [70]:
a

tensor([[3., 4.],
        [6., 8.]])

In [73]:
torch.norm(a, dim=1, keepdim=True)

tensor([[ 5.],
        [10.]])

In [88]:
a = torch.tensor([[1,1],[1,1]])

In [89]:
a

tensor([[1, 1],
        [1, 1]])

In [92]:
b = torch.tensor([[2,3], [2,3], [2,3]])

In [93]:
b

tensor([[2, 3],
        [2, 3],
        [2, 3]])

In [94]:
a.mm(b.t())

tensor([[5, 5, 5],
        [5, 5, 5]])

In [95]:
a = torch.randint(10, (5, 10))

In [96]:
a

tensor([[1, 2, 0, 8, 5, 5, 4, 9, 6, 6],
        [9, 3, 2, 3, 1, 9, 1, 3, 6, 8],
        [7, 2, 6, 4, 5, 9, 2, 4, 9, 2],
        [8, 6, 1, 1, 5, 1, 7, 1, 8, 0],
        [2, 8, 4, 1, 2, 0, 1, 6, 8, 6]])

In [97]:
a.max

<function Tensor.max>

In [102]:
a.max(1)[1]

tensor([7, 0, 5, 0, 1])

In [128]:
class Result:
    def __init__(self,):
        self.cm = np.array([[2, 9],[3,4]])
    
    @property
    def recalls(self): 
        return np.diag(self.cm) / np.sum(self.cm, axis=1)
    
    @property
    def mean_recall(self):
        return np.mean(self.recalls)

In [129]:
res = Result()


In [130]:
res.recalls

array([0.18181818, 0.57142857])

In [131]:
res.mean_recall

0.37662337662337664

In [144]:
a = torch.tensor([1.00, 2.00])

In [150]:
arr = np.zeros((4,4))
arr[a.int()[1]][1] += 1

In [151]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.]])

AttributeError: 'numpy.ndarray' object has no attribute 'int'

In [153]:
d = {1: 222}

In [163]:
d.update({1: 2})

In [180]:
d.setdefault

<function dict.setdefault(key, default=None, /)>

In [183]:
d.pop(1, 3)

2

In [184]:
d

{}